sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t diogoacneto/docker-react -f Dockerfile.dev .

script:
  - docker run -e CLI=true diogoacneto/docker-react npm run test 